// <auto-generated />
using System;
using AccessService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccessService.Infrastructure.Migrations
{
    [DbContext(typeof(AccessRightDbContext))]
    [Migration("20260612125457_Events")]
    partial class Events
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessService.Domain.Models.AccessRight", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("id");

                    b.Property<string>("GuidelineClassificationId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("guideline_classification_id");

                    b.Property<string>("GuidlineClassificationPropertyId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("guidline_classification_property_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("Right")
                        .HasMaxLength(40)
                        .HasColumnType("integer")
                        .HasColumnName("right");

                    b.Property<Guid>("UseCaseId")
                        .HasMaxLength(40)
                        .HasColumnType("uuid")
                        .HasColumnName("usecase_id");

                    b.Property<Guid>("UserGroupId")
                        .HasMaxLength(40)
                        .HasColumnType("uuid")
                        .HasColumnName("usergroup_id");

                    b.HasKey("Id");

                    b.ToTable("accessright", (string)null);
                });

            modelBuilder.Entity("AccessService.Domain.Models.GuidelineClassification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClassificationId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("classification_id");

                    b.Property<string>("Code")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("GuidelineVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("guideline_version_id");

                    b.Property<string>("Identifier")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("identifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("RelationsJson")
                        .HasColumnType("text")
                        .HasColumnName("relations_json");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("GuidelineVersionId", "ClassificationId")
                        .IsUnique();

                    b.HasIndex("GuidelineVersionId", "Identifier");

                    b.ToTable("guideline_classification", (string)null);
                });

            modelBuilder.Entity("AccessService.Domain.Models.GuidelineClassificationProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignmentJson")
                        .HasColumnType("text")
                        .HasColumnName("assignment_json");

                    b.Property<string>("ClassificationPropertyId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("classification_property_id");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("default_value");

                    b.Property<Guid>("GuidelineClassificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("guideline_classification_id");

                    b.Property<bool>("IsReadonly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_readonly");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("property_id");

                    b.Property<string>("PropertySetId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("property_set_id");

                    b.Property<string>("Reference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reference");

                    b.Property<int>("SortNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sort_number");

                    b.HasKey("Id");

                    b.HasIndex("GuidelineClassificationId", "ClassificationPropertyId")
                        .IsUnique();

                    b.ToTable("guideline_classification_property", (string)null);
                });

            modelBuilder.Entity("AccessService.Domain.Models.GuidelineProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("ExtraJson")
                        .HasColumnType("text")
                        .HasColumnName("extra_json");

                    b.Property<Guid>("GuidelineVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("guideline_version_id");

                    b.Property<string>("Identifier")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("identifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("property_id");

                    b.Property<string>("PropertyType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("property_type");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("StorageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("storage_type");

                    b.Property<string>("UnitAbbreviation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit_abbreviation");

                    b.Property<string>("UnitType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unit_type");

                    b.HasKey("Id");

                    b.HasIndex("GuidelineVersionId", "PropertyId")
                        .IsUnique();

                    b.ToTable("guideline_property", (string)null);
                });

            modelBuilder.Entity("AccessService.Domain.Models.GuidelinePropertySet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("GuidelineVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("guideline_version_id");

                    b.Property<string>("Identifier")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("identifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("PropertySetId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("property_set_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("GuidelineVersionId", "PropertySetId")
                        .IsUnique();

                    b.ToTable("guideline_property_set", (string)null);
                });

            modelBuilder.Entity("AccessService.Domain.Models.GuidelineVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bucket_name");

                    b.Property<string>("ComplexDataJson")
                        .HasColumnType("text")
                        .HasColumnName("complex_data_json");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("DomainJson")
                        .HasColumnType("text")
                        .HasColumnName("domain_json");

                    b.Property<string>("Etag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("etag");

                    b.Property<DateTimeOffset>("EventTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_timestamp");

                    b.Property<string>("GuidelineId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("guideline_id");

                    b.Property<string>("Identifier")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("identifier");

                    b.Property<string>("MappingsJson")
                        .HasColumnType("text")
                        .HasColumnName("mappings_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("object_name");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ServiceId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("service_id");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt")
                        .IsDescending();

                    b.HasIndex("ServiceId")
                        .IsUnique()
                        .HasFilter("service_id IS NOT NULL");

                    b.HasIndex("ObjectName", "Etag")
                        .IsUnique();

                    b.HasIndex("ObjectName", "ProcessedAt")
                        .IsDescending(false, true);

                    b.ToTable("guideline_version", (string)null);
                });

            modelBuilder.Entity("AccessService.Domain.Models.KafkaDeadLetter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("consumer_name");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("Key")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("key");

                    b.Property<long>("Offset")
                        .HasColumnType("bigint")
                        .HasColumnName("offset");

                    b.Property<int>("Partition")
                        .HasColumnType("integer")
                        .HasColumnName("partition");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("topic");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("FailedAt");

                    b.ToTable("kafka_dead_letter", (string)null);
                });

            modelBuilder.Entity("AccessService.Domain.Models.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic");

                    b.HasKey("Id");

                    b.ToTable("outbox_event");
                });

            modelBuilder.Entity("AccessService.Domain.Models.UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("usergroup", (string)null);
                });

            modelBuilder.Entity("AccessService.Domain.Models.GuidelineClassification", b =>
                {
                    b.HasOne("AccessService.Domain.Models.GuidelineVersion", "GuidelineVersion")
                        .WithMany("Classifications")
                        .HasForeignKey("GuidelineVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuidelineVersion");
                });

            modelBuilder.Entity("AccessService.Domain.Models.GuidelineClassificationProperty", b =>
                {
                    b.HasOne("AccessService.Domain.Models.GuidelineClassification", "GuidelineClassification")
                        .WithMany("ClassificationProperties")
                        .HasForeignKey("GuidelineClassificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuidelineClassification");
                });

            modelBuilder.Entity("AccessService.Domain.Models.GuidelineProperty", b =>
                {
                    b.HasOne("AccessService.Domain.Models.GuidelineVersion", "GuidelineVersion")
                        .WithMany("Properties")
                        .HasForeignKey("GuidelineVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuidelineVersion");
                });

            modelBuilder.Entity("AccessService.Domain.Models.GuidelinePropertySet", b =>
                {
                    b.HasOne("AccessService.Domain.Models.GuidelineVersion", "GuidelineVersion")
                        .WithMany("PropertySets")
                        .HasForeignKey("GuidelineVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuidelineVersion");
                });

            modelBuilder.Entity("AccessService.Domain.Models.GuidelineClassification", b =>
                {
                    b.Navigation("ClassificationProperties");
                });

            modelBuilder.Entity("AccessService.Domain.Models.GuidelineVersion", b =>
                {
                    b.Navigation("Classifications");

                    b.Navigation("Properties");

                    b.Navigation("PropertySets");
                });
#pragma warning restore 612, 618
        }
    }
}
